### ISSUE TITLE
Open the browser for me?

### ISSUE THREAD

**Issue by mightyiam** [buggerjs/node-inspect#9]
Pretty please?

**Comment by jkrems** [comment]
I think this is a misunderstanding - maybe you wanted to open this issue against node when using `node --inspect my-script.js`? `node-inspect` is a command line debugger, there's no browser involved. :)

**Comment by mightyiam** [comment]
Funny. I was looking for a cli wrapper of  `node --inspect foo.js`, for comfort. I guess I understood what I desired to understand.
